### ISSUE TITLE
Map Pool

### ISSUE THREAD

**Issue by denkstrum-hots** [chairleague/hots-rules#10]
The large map pool size makes it cumbersome to plan and react to drafts, HGC limits their map pool and that has seemed popular with teams.  As a caster, most teams gravitate to the same 5 ish maps anyways.

For simplicity sakes, I think rather than a per night or per division separate map pool, just take a survey for all the captains on the 5 maps they want removed from the map pool, ranked in order of priority.  Take the top 4 choices and remove those from chair league globally.  Any new maps released during the season will be allowed into the map pool.

A smaller pool makes it easier for teams to prep and practice and most people dislike three maps in particular.    Those maps contribute to cheese more than others as well.  Allowing new maps creates viewer interest and lets chairleague serve as an example for learning to play them.

**Comment by superjova** [comment]
Something I'm not sure where I read or head of it is map pool per week. When a week is scheduled, it can randomize "5 maps" from the pool to pick from.

The number each week can be discussed here if that's something people like.

**Comment by superjova** [comment]
We would also need a rule for "No map can be played 2 times in a series"

**Comment by Durgulach** [comment]
The no repeat map rule is in the proposed language I drafted in another topic.

I wouldnt be a proponent of a weekly pool, too much for teams to keep track of.  I would be a fan of a simpler locked to HGC pool

**Comment by onemegamanfan** [comment]
I say just a set locked pool per season.  Maybe just copy the current HGC pool?  As someone who plays in HGC open having the pools match would be nice.  Maybe the Free league can be any map paid has a set list?

**Comment by Akash122** [comment]
Copying the HGC pool or Hero/Team league pool is what should be done. Those are the maps people will be playing the most and be most comfortable on.

**Comment by Hammwich** [comment]
I agree with Akash and Megamanfan, I think its in the best interest of the league to adopt what is considered to be the most competitively balanced maps. 

In addition, I'd bet that nearly 70% of all matches played last season were played on the 9 maps that are available in the HGC map pool.

**Comment by superjova** [comment]
Can you post your suggested map pool here?

**Comment by Hammwich** [comment]
Warhead Junction
Braxis Holdout
Cursed Hollow
Dragon Shire
Tomb of the Spider Queen
Sky Temple
Towers of Doom
Battlefield of Eternity
Infernal Shrines

Edit, beat you to it Durg ;)

**Comment by Durgulach** [comment]
Here.is the current HGC pool:

Battlefield of Eternity
Braxis Holdout
Cursed Hollow
Dragon Shire
Infernal Shrines
Sky Temple
Tomb of the Spider Queen
Towers of Doom
Warhead Junction

**Comment by superjova** [comment]
With a proposed map pool, does it update as HGC updates or does it change
from season to season?

**Comment by Hammwich** [comment]
Personally, I would prefer it follow HGC, they define the most competitively balanced maps, if we just follow their lead it limits the need for debate down the road. And helps us align with Open Division as well.

**Comment by Akash122** [comment]
I'd go with whatever the HGC map pool is at the start of a CL season, and leave it that way for the duration of that season. If it so happens that HGC changes their map pool in the middle of a CL season I would wait until the following CL season to make the change.

**Comment by Durgulach** [comment]
I wouldnt even mention HGC.  Just say this is the map pool for the season, and just copy hgc.  This way if hgc pool does change there is no confusion in our league and we can change the pool the following season.

**Comment by Hammwich** [comment]
I don't think anyone is suggesting that we reference the HGC at all, not being affiliated with it, more just follow their lead.

**Comment by superjova** [comment]
Season 1, the map was picked before the week started. Did anyone play
during that time?

What do you think about this:

Given there are 3 rounds per map, each week gets a random 5 of the 13 maps
for the map pool. Going into the week, you will know what are the potential
maps the other team can pick. This will allow us to have a map pool while
at the same time giving variety each week.

**Comment by Hammwich** [comment]
To be honest @superjova I don't think that would bring variety or additional players to the league. I don't recall playing a single map that wasn't on the HGC pool in all 8 weeks last season, and not in playoffs either and over that time played 5 best of 3s. 

Emulating professional play is a big part of leagues like this, the maps picked would likely be the 9 already in the proposed map pool. 

Unless you have a week that is Haunted Mines, Hanamura, Garden Terror, Blackhearts Bay + 1, I don't see these maps being picked. And honestly I know my team wouldn't be too thrilled with with the prospect of playing those maps.

**Comment by Akash122** [comment]
I agree. Imo, the vast majority of players have no desire to play garden, mines, etc. I don't see a reason to include them.

**Comment by superjova** [comment]
I'm down to make a map pool. Can we get a pull request with the
specifications? Also, chairleague.com/maps will always show the map pool.
Include that in the rules.

Some additional rules:
- Teams will only be able to select maps from the map pool
- Same map cannot be played twice in the same series

**Comment by Hammwich** [comment]
With the Fixed map pool, I think its also time to add 1 Map Ban per team prior to the start of Game 1. 

This eliminates the need for a "default map" as suggested in a separate thread. 

A match would begin, prior to entering a lobby each team in the /ChairLeague channel will Ban 1 map from the map pool. After banning 1 map, the Home Team will choose the map to be played and a lobby will be created. 

I would like this to evolve into the Loser of Game 1 having the choice of Map Pick or First Pick in the subsequent match. This allows a team if the meta is very "first pick friendly" to take that advantage and surrender map choice.

**Comment by superjova** [comment]
Let's start with a map pool first. The other topics should be discussed in
their own issues.

**Comment by Hammwich** [comment]
Would love to help you @superjova with the pull request but I don't know how to do that.

**Comment by superjova** [comment]
I've implemented map pools on my end. Can we have a pull request made with the map pool rules and current allowed maps?

**Comment by superjova** [comment]
To do a pull request, go to Code => README => Edit. And then create your first pull request when you are done.

**Comment by superjova** [comment]
Added in PR https://github.com/chairleague/hots-rules/pull/24
