### ISSUE TITLE
Schedule 

### ISSUE THREAD

**Issue by denkstrum-hots** [chairleague/hots-rules#18]
Need to input what the new schedule is, I missed that part of the meeting, I don't know what the Saturday decision is, but that will need to be incorporated into the rules.

**Comment by superjova** [comment]
You will be signing up for a day. If there are 4 leagues Tues | Thurs | Fri | Sat. You choose however many your team or teams want to play in. Then you are only scheduled on the days you picked.

**Comment by Durgulach** [comment]
When did we switch from MWF to TThFS?

This due to HGCo and Hype overlap?

**Comment by johnafogarty4** [comment]
Well now i'm wondering the same, I thought it was MWF.  Is TThFS the new schedule?

**Comment by superjova** [comment]
It was a hypothetical scenario. We could do 7 days a week even. Was just laying out an example

**Comment by superjova** [comment]
Tues / Thurs is current schedule. No rules will be added for the leagues as the website https://play.chairleague.com has the leagues listed with days
