### ISSUE TITLE
Number of games For a match

### ISSUE THREAD

**Issue by denkstrum-hots** [chairleague/hots-rules#7]
Should matches be aimed at a best of three format or two game series?  

It seems a consensus has developed against having single game matches, in favor of multiple matches.  The points seem to devolve into either having a best of three or two games series.  Each with advantages and disadvantages.

Best of three:  a common format with a clear result that has been utilized previously in chairleague.  Easy to understand.  Teams and viewers seem to enjoy the tension that rises once you go to game three.  A third game really seems to be the matches that teams have felt each other out and adapted fully for.  Best of three can have indeterminate lengths that make it harder to plan for both teams and casters as the match could end after game two or go long into a game three.  Depending on match scoring, losing 2-1 can be just as bad as being swept and closer series and games aren't  reflected in the standings and points.  The choice of map pick/first or second hero pick/server pick will always receive complaints about benefiting one team over the other in the course of the series since one team will gain that perceived advantage twice.  

Two game series:  predictable time periods make for easier planning and even distribution of map/hero/server selection since each team will have one opportunity at each role.  Two game series can easily be fit in an hour to anhour 15, making scheduling and casting multiple matches much easier, a far smoother viewing experience between matches in this case.  Easier implementation of points/ranking system that could more accurately reflect series results.  Tied series create rivalries and storylines since determination about superior team is not resolved.  Could allow for more round robin style play rather than ladder set up.  The two game series don't give teams that third game to show their adaptions to the other teams and some teams desire that determination of superiority between them in that series rather than delaying it for another match down the season.  This format is probably viewed as more recreational rather than competitive due to esport development.  

My suggestion and desire as both a player and a caster are two game series.  It gives predictable time periods to plan around for my personal life and my team personal life, levels the playing field for map/hero/server selection, makes for a far smoother casting production and viewing experience when doing multiple matches a night, and I believe creates more opportunity for storylines to develop between teams in the league.

**Comment by superjova** [comment]
How many points per each win in a bo2? Do you get any bonus points for winning both games in a 2 game series?

I do like bo2 because it's a guaranteed amount of games. No variability. It also is a nice compromise for EST vs. PST when EST plays late at night. Would require minor updates to code.

**Comment by Durgulach** [comment]
I dont understand 2 game series argument.

As for the standings, there is no accuracy difference as stated above.  In a best of three the points are: 0-2=0 1-2=1 2-1=2 2-0=2.   There is no getting to game 3 and losing punishment.

It seems the primary drive behind 2 game series is caster scheduling.  But ditching Bo3 will not address the issue in practice.  Depending on maps and parity some 2 game series will go significantly longee than others.  In a game whwre the time for each map is not set you will never get it to a point where it is smoothly scheduled in the way you guys seem to think a Bo2 would.  Is it worth giving up a few awsome 3 game series a season for, no way

**Comment by onemegamanfan** [comment]
Im with Durgulach.  BO3 is the best option.

**Comment by superjova** [comment]
Closing this issue as we are keeping it best of 3.
