### ISSUE TITLE
Substitution Players

### ISSUE THREAD

**Issue by denkstrum-hots** [chairleague/hots-rules#8]
It seemed separate issue from roster lock so I made this issue topic.

All teams have had issues with scheduled players not being able to make games due to work and life commitments,so subs outside the rosters seem like a likely need.

I suggest that subs follow all division restriction guidelines, such as nommaster/gm in div 3 and below.  
A player may not sub for another team in the same night and division that they are already playing in.
  This prevents rigging game accusations and shenanigans.  

Only 1 sub allowed per series.
 Sub can be replaced by a regular rostered player mid series and Vica versa.

I don't think you should limit the amount of different teams a player could sub for, and you May even want to start a 'sub' designation that players could sign up/pay for to make it easier for some teams to find a sub and designate people that are available to sub.

**Comment by johnafogarty4** [comment]
I like the idea of a 'sub' designation.

**Comment by superjova** [comment]
How would this change affect the 5/5 locked in players for the night if that rule comes into play?

**Comment by Durgulach** [comment]
We need to make a distinction here.  What do we mean by "sub"?  Does a sub mean a non-rostered player?  If I have 6 rostered members available can I swap a player from game 1 out for another rostered player for game 2 of a series etc.?

**Comment by Durgulach** [comment]
Rostered players should be able to come off the bench at will between games.  I know when my team scrims we usually use 1-2 subs between games 1 and 2 and then 1-2 for game 3 but it is all the same 6-7 players.  X plays games 1 and 3 y plays game 2 etc

**Comment by pkatz19c** [comment]
I really appreciate the move to protect us Div 3 scrubs. Master may not even be a low enough cut-off; quite honestly, I suspect a high-diamond sub could carry a previously all-silver team far above an all-gold team. If you do want an Easy/Medium/Hard, but only Masters is the cutoff for Easy, doesn't that make Easy for Bronze/Silver/Gold/Diamond? That's a huge range!

**Comment by superjova** [comment]
Closing. Rules updated with 4/5 and substitution rules
